export const GenshinData: {
    name: string;
    nameShort?: string;
    rarity: number;
}[] = [
        { name: 'Aether', rarity: 5 },
        { name: 'Albedo', rarity: 5 },
        { name: 'Aloy', rarity: 5 },
        { name: 'Amber', rarity: 4 },
        { name: 'Ayaka', rarity: 5 },
        { name: 'Barbara', rarity: 4 },
        { name: 'Beidou', rarity: 4 },
        { name: 'Bennett', rarity: 4 },
        { name: 'Childe', rarity: 5 },
        { name: 'Chongyun', rarity: 4 },
        { name: 'Diluc', rarity: 5 },
        { name: 'Diona', rarity: 4 },
        { name: 'Eula', rarity: 5 },
        { name: 'Fischl', rarity: 4 },
        { name: 'Ganyu', rarity: 5 },
        { name: 'Hu Tao', rarity: 5 },
        { name: 'Jean', rarity: 5 },
        { name: 'Kaeya', rarity: 4 },
        { name: 'Kazuha', rarity: 5 },
        { name: 'Keqing', rarity: 5 },
        { name: 'Klee', rarity: 5 },
        { name: 'Lisa', rarity: 4 },
        { name: 'Lumine', rarity: 5 },
        { name: 'Mona', rarity: 5 },
        { name: 'Ningguang', rarity: 4 },
        { name: 'Noelle', rarity: 4 },
        { name: 'Qiqi', rarity: 5 },
        { name: 'Raiden Shogun', nameShort: 'Raiden', rarity: 5 },
        { name: 'Razor', rarity: 4 },
        { name: 'Rosaria', rarity: 4 },
        { name: 'Sara', rarity: 4 },
        { name: 'Sayu', rarity: 4 },
        { name: 'Sucrose', rarity: 4 },
        { name: 'Venti', rarity: 5 },
        { name: 'Xiao', rarity: 5 },
        { name: 'Xingqiu', rarity: 4 },
        { name: 'Xinyan', rarity: 4 },
        { name: 'Yanfei', rarity: 4 },
        { name: 'Yoimiya', rarity: 5 },
        { name: 'Zhongli', rarity: 5 }
    ];